providers = ["java"]

[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmds = [
    "cd webapp/transpiler/src/parser && java -Xmx500M -cp antlr-4.13.2-complete.jar org.antlr.v4.Tool -Dlanguage=Python3 -o generated_ewhile_parser -package generated_while_parser ewhile.g4 -visitor"
]

[start]
cmd = "echo 'Build complete. Webapp directory is ready to be served as static content.'"
